name: JS CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  typescript-ci:
    name: Typescript ${{ matrix.node }}

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        node:
          - 14
          - 16
          - 18

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn test
      # - run: yarn lint
      # - run: yarn format:check
      # - run: yarn build:all
